/*
Создать запрос для выделения из символьной строки повторяющихся, стоящих рядом одинаковых слов.
*/
DEFINE str ='er   er erer              erer er er ererer     ererer       ererer er er erererer    erererer er er e re re r r';
WITH ALL_WORDS AS
(SELECT REGEXP_SUBSTR((REGEXP_REPLACE(' ' || '&str' || ' ', '\s+', ' ')), '\S+', 1, level) WORD, LEVEL POSITION
FROM DUAL
CONNECT BY LEVEL < REGEXP_COUNT((REGEXP_REPLACE(' ' || '&str' || ' ', '\s+', ' ')), '\s')),
WORDS_FIRST AS
(SELECT AW1.WORD, AW1.POSITION, (CASE WHEN (AW2.WORD IS NOT NULL OR AW1.POSITION = 1) THEN 1 ELSE 0 END) FIRS
FROM ALL_WORDS AW1
LEFT JOIN ALL_WORDS AW2 ON (LOWER(AW1.WORD) != LOWER(AW2.WORD) AND AW1.POSITION = AW2.POSITION + 1)
ORDER BY AW1.POSITION),
ALL_SEQUENCES AS
(SELECT SYS_CONNECT_BY_PATH(WORD, ' ') WORDS, CONNECT_BY_ROOT (POSITION) ROOT, LEVEL LVL
FROM WORDS_FIRST
START WITH FIRS = 1
CONNECT BY PRIOR POSITION = POSITION - 1 AND PRIOR UPPER(WORD) = UPPER(WORD)),
RESULT AS
(SELECT WORDS
FROM ALL_SEQUENCES
WHERE (ROOT, LVL) IN (SELECT ROOT, MAX(LVL)
FROM ALL_SEQUENCES
GROUP BY ROOT
HAVING MAX(LVL) > 1)
ORDER BY ROOT)
SELECT CASE WHEN ROWNUM = 1 THEN '&str' ELSE ' ' END "Символьная строка", WORDS "Повторяющиеся слова"
FROM RESULT;

